---
version: "3.1"
services:
   gphoto-x:
      image: ghcr.io/gilesknap/gphotos-sync
      container_name: gphoto
      volumes:
          - ./storage:/storage
	  - ./config:/config
      ports:
	  - 4563:8080
      restart: unless-stopped
